### PR TITLE
Feature/develop/tsk2

### PR DESCRIPTION
**Pull request by SvyatoS1**
Done task 2.

### CODE REVIEW

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
remove bin and obj folders

**Comment by SvyatoS1** [comment]
> remove bin and obj folders

Done

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
> > remove bin and obj folders
> 
> Done

check test project

**Comment by SvyatoS1** [comment]
> > > remove bin and obj folders
> > 
> > 
> > Done
> 
> check test project

Done

**Review by andrii-s-spitzer-lpnu-ua — APPROVED** [review]

**Pull request merged**
